### ISSUE TITLE
Impossible to mock CreatedDate and LastUpdateDate

### ISSUE THREAD

**Issue by LewandowskiAnthony** [Decathlon/tzatziki#150]
Hello,

When using @CreatedDate and @LastUpdateDate annotation with JPAAuditing, it is impossible to override the current time with our own value.
Test example : 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/79880195/225607533-8d66166a-bbe0-49ef-a0ff-ea032bb60ffb.png">
Entity : 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/79880195/225607623-d49e3647-2c9e-4048-894b-2d5d8a255017.png">
The entity saved in database
<img width="914" alt="image" src="https://user-images.githubusercontent.com/79880195/225608277-e04cbfb6-5114-4f01-b4f7-02c3559fb68d.png">
EnableAuditing, JpaTests and any classic test annotations can save the day.

**Comment by brian-mulier** [comment]
Hello ! Can you share what this step does ?
<img width="294" alt="image" src="https://user-images.githubusercontent.com/69139631/225628905-41714207-f327-4bba-90a5-b36b088e5b4e.png">
Perhaps you meant `* the current time is...` ?

**Comment by LewandowskiAnthony** [comment]
Hello, It was a test step written by me to define sys time to a mocked date. You can ignore that

**Comment by brian-mulier** [comment]
If you're still using it, can you please provide its implementation so we better understand the issue and what can be done around it ?

**Comment by LewandowskiAnthony** [comment]
No, I'm not still using it, in fact, I deleted it

**Comment by mimfgg** [comment]
Then, I close this ticket!
