### ISSUE TITLE
Incompatibility with snakeyaml 2.0

### ISSUE THREAD

**Issue by sofianeyousfi** [Decathlon/tzatziki#154]
In our project, prisma indicates a vulnerabylity in snakeyaml and suggested to use the version 2.0

![image](https://user-images.githubusercontent.com/113367333/228296110-f03fc00e-52ad-461a-aa24-fbe6013b2c18.png)

The problem is that Tzatziki seems incompatible with it

![image](https://user-images.githubusercontent.com/113367333/228297392-4e6f7795-21ed-48af-bfcf-5e0bbbb36e9c.png)

Can you upgrade?

**Comment by brian-mulier** [comment]
Also, please note that it is probably not that much of an issue unless another framework than Spring Boot uses this dependency : https://github.com/spring-projects/spring-boot/issues/34405#issuecomment-1450280581

**Comment by brian-mulier** [comment]
(tell us if it's okay for you so we can close this issue if it is)
