### ISSUE TITLE
Optimistic Locking issue

### ISSUE THREAD

**Issue by Z15MNKOU** [Decathlon/tzatziki#166]
After adding the Optimistic Locking management through @Version column.
It became impossible to insert value then refers it in another Given like this : 
![Pasted Graphic](https://github.com/Decathlon/tzatziki/assets/58467911/30961b30-b474-40f9-bd95-742d0c23d419)

When doing so, we got the following error : 
`org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.decathlon.shipit.domain.StandardObjectEntity.shipment -> com.decathlon.shipit.domain.ShipmentObjectEntity`

The workaround that we use in order to still have our test working is to define the child entity in parent for saving : 
![Pasted Graphic 1](https://github.com/Decathlon/tzatziki/assets/58467911/949ce34d-7e95-4819-9f16-13d88366e50e)
We had to add the Cascade to the parent Aswell : 
![Pasted Graphic 2](https://github.com/Decathlon/tzatziki/assets/58467911/4f1cd30d-f1e9-4009-855a-1bc08874dd51)

So now the parent Entity handle the versioning of the child and does not refer to an entity save previously.
After some check we understand that when adding the Version definition, Hibernate do some additional check that cause the `JpaSteps.saveAll` to failed.
The workaround that we use is not optimal, as it forces us to modify our domain logic.

**Comment by brian-mulier** [comment]
I think a flush is missing in the 'will contain' step but I may be wrong.
Your example is correct and should work as-is. My guess is that the child object is not flushed properly before you're trying to insert the parent but I got to give it a try.

**Comment by brian-mulier** [comment]
Can you tell me if your @Version was added to the parent or child object pls ?

**Comment by brian-mulier** [comment]
Can you try to add this to your JoinColumn params pls ? insertable = false, updatable = false

**Comment by Z15MNKOU** [comment]
We were wrong about the definition of our object if we want to use version column and therefore optimistic locking
We have to define version in the entity that we create, since it is the normal behavior in the first place.
(Null is not allowed in column version)

In order to remove the cascade workaround that we put, we had to define entity properly add the version : 
<img width="743" alt="Pasted Graphic" src="https://github.com/Decathlon/tzatziki/assets/58467911/ccd09252-dabc-4229-982c-ef8ce481d6dd">

Since we have a recursive relation to one of our entity, we add to adjust it as-well by creating the parent first then refers to it in child :
<img width="655" alt="Pasted Graphic 1" src="https://github.com/Decathlon/tzatziki/assets/58467911/f07a0434-d01f-49f9-ac77-3f335b180e55">

With those modifications we were able to remove the @Cascade from our entities and solve our issue.
Thanks for the time !
