### ISSUE TITLE
Some variable names can break the lib

### ISSUE THREAD

**Issue by hqrd** [Decathlon/tzatziki#25]
Hello,

When updating to 1.0.8, an error occurred in some old tests concerning the connection to the application during http calls.
```
When MYUSER posts on "/myapi"...
```
```
java.lang.AssertionError: Connection refused
Caused by: java.net.ConnectException: Connection refused
```

It appears to be caused by a variable initialized at the start of the feature, with the name "local", which was overriding the "local.port" variable used by the lib to retrieve the spring application port.
```
  Background: Init variables
    * local is "AT"
```

To fix this I renamed it to `locale`, but I guess it can be managed differently in the lib ? I also guess it's not the only name that can cause this kind of problems.

**Comment by brian-mulier** [comment]
Hello !

Yes it is due to dot-notation which constructs a local object being overriden by your variable. Perhaps we could add a special namespace ahead in order not to override user-defined variables ? @mimfgg

**Comment by mimfgg** [comment]
oh ... sorry about that ... it should be `locale` anyway, but yes, I can see how that would happen.
what about prefixing internal variables with `_` ?

**Comment by brian-mulier** [comment]
👍
