### ISSUE TITLE
[Tzatziki JPA] Keyword 'only' does not work on multi-schemas databases

### ISSUE THREAD

**Issue by mfnztdkt** [Decathlon/tzatziki#344]
Context : a multi-schemas database

The method the_repository_will_contain_with_type launches a Truncate in case of InsertionMode.ONLY .
That Truncate does not take schema into account, leading to that error "StatementCallback; bad SQL grammar [TRUNCATE **TABLE** RESTART IDENTITY CASCADE]", when trying to truncate a table located in another schema than the one defined in the datasource.

I don't know if it is the best solution, however the following solves the issue :
- add a utility method "private String getSchemaName(Class<?> clazz) " returning the schema associated to the JPA Entity
- modify the method the_repository_will_contain_with_type in order to take the schema into account in the TRUNCATE request

Can you tell if you plan to add that feature in Tzatziki soon ?

**Comment by alexandrepa** [comment]
Hi, this issues is closely linked to issue #340, I will do a global fix to handle multiple schema database. Can be confident that the fix will be release in a new version before the end of the week.

**Comment by mfnztdkt** [comment]
Great, thank you !

**Comment by alexandrepa** [comment]
v1.6.0 should resolve your issue.
