### ISSUE TITLE
Proposal: tzatziki-sql module

### ISSUE THREAD

**Issue by jak78dkt** [Decathlon/tzatziki#385]
Some microservices don’t use JPA. Alternatives to JPA include JOOQ, R2DBC, and plain old SQL. It would be great for these microservices to benefit from Tzatziki.

My proposal is to create a `tzatziki-sql` module based on good old JDBC, making it agnostic to the persistence framework used by the production code.

Open questions: 
- Should we make it depend on Spring or not?
- the syntax might conflict with `tzatziki-spring-jpa` because it already uses a 'table-like' syntax: `Given that the users table will contain:`. Should we use the same syntax and assume that people won't include both `tzatziki-spring-jpa` and `tzatziki-sql`? Or should we opt for sth like: `Given that the users SQL table will contain:` - not ideal

**Comment by alexandrepa** [comment]
We are currently working on the new structure of the tzatziki db modules. You can find a first draft here :
https://github.com/Decathlon/tzatziki/wiki/Tzatziki-DB-Module

Feel free to give us some feedback based on your usecases.

**Comment by jak78dkt** [comment]
Great! However, I'm not sure the JPA module should depend on a "pure DB" module that provides pure-SQL steps. What would be the best channel to discuss the strategy on Tzatziki DB modules?

**Comment by alexandrepa** [comment]
I just created a discussion so we can discute about it : https://github.com/Decathlon/tzatziki/discussions/389
