### ISSUE TITLE
using tzatziki with Oracle

### ISSUE THREAD

**Issue by z05sgoul** [Decathlon/tzatziki#56]
Hello,
I am using Tzatziki for our tests. Recently, following a typing problem, we had to align our test database with the real one... Unfortunately, with an Oracle database, we encounter errors when initiating our data with step :
`that the [table] table will contain only:  `
error :
`      org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select tablename from pg_catalog.pg_tables where schemaname='public']; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: Non-existent table or view.`

Thank you for your work
Best regards,
Sylvain G.

**Comment by brian-mulier** [comment]
Hello !

Just in case, are you under the 'public' database schema ?

Brian

**Comment by z05sgoul** [comment]
Hello, 
I am well under the "public" db scheme, but the problem comes from there :
![image](https://user-images.githubusercontent.com/48682943/161552145-2d2d8194-8336-474d-932b-78e601768a8f.png)
where "pg_catalog.pg_tables" is posgres specific.

Sylvain

**Comment by brian-mulier** [comment]
Hello !

Can you try to build locally the lib and tell me if it's working with this branch ? I've tried something which should work for all databases : https://github.com/Decathlon/tzatziki/tree/ft/oracleSupport

Looking forward for your feedback, if it's working it will be released.

Thank you
