### ISSUE TITLE
bug: "after \\d+ms|" checks are not always done.

### ISSUE THREAD

**Issue by ThomasCaud** [Decathlon/tzatziki#59]
It seems that guard which contain "after Xms" are not check.
It seems that when using this keyword, the check are done in async, by using another thread from the main one.
I suppose that as the main thread is over before the Xms duration, then the "sub threads" are over too, and so the checks are not done.

![unnamed](https://user-images.githubusercontent.com/20739026/161995778-dc208942-acdf-46e6-bec1-f161c07d04e3.png)

PS: Maybe we should have some "labels" available in order to organize the issues?

**Comment by brian-mulier** [comment]
Hello !

Yes it could be a bit confusing, perhaps we should enhance the documentation about this behaviour.
In fact the "after Xms" guard should only be used to make an async action after a given amount of time and never used for assertions.

You could rather use "during Xms" which checks for a condition to be true after 500ms max and for the given duration.
The most appropriate is probably "within Xms" which ensure that within the given time the assertion was true, thus returning instantly when it is.

Beware that using during Xms will make your tests Xms longer cause it will wait the given time wether the condition is met or not so you should avoid using it if possible.

If none of the above guards meet your needs, we can still add a guard for "later" assertions which would run on the main thread and effectively block the test.

Labels may be a great idea :) @mimfgg

**Comment by mimfgg** [comment]
just a thought ... maybe we should wait for the "after Xms" step to be run and gather any exception thrown in the @After ... now it is a better error prone, on top of the documentation being unclear.

**Comment by brian-mulier** [comment]
It could be part of the solution but I feel like it is unclear that after Xms is a non blocking step, but I can't think of another way to tell that it runs asynchronously, or maybe we could default the after to being run synchronously (meaning we'll wait the given amount, execute the step then proceed) and add another guard "asynchronously".

It could then use the guard chaining to make an "another-thread after step" like this : 
"Given that, asynchronously, after 500ms myVar == 'true'" ?

**Comment by brian-mulier** [comment]
Btw doing like this would delegate all the "wait until async is finished" part to the newly created guard

**Comment by brian-mulier** [comment]
Moreover (and that's my final thought), it would allow us to do multiple assertions in parallel without delay : 
"Then, asynchronously, the kafka topic 1 contains this message"
"And, asynchronously, the kafka topic 2 contains this message"
Would help greatly considering performance issue we had recently over topic awaiting 👍

**Comment by ThomasCaud** [comment]
Hey guys, thanks for your quick answers!

> I guess that the documentation https://github.com/Decathlon/tzatziki/tree/main/tzatziki-core#delay-a-step-asynchronously is not really well written then :) In any way the "after Xms" is just an async fire and forget call that will be done after a while.
> 
> Not sure what you mean about labels ... Like issue labels? we have them

<img width="226" alt="Capture d’écran 2022-04-06 à 17 32 57" src="https://user-images.githubusercontent.com/20739026/162012248-85d573b8-1b2b-4f8f-9e8a-88a6b2b6053e.png">

I can't add them by myself. Is this for contributors only?

**Comment by mimfgg** [comment]
I think so.
