### ISSUE TITLE
using tzatziki with Oracle (part 2)

### ISSUE THREAD

**Issue by z05sgoul** [Decathlon/tzatziki#72]
Hello,

thanks for your work on the issue #56. Now we can go a little bit further !
But there are still sql scripts in hard that are not compatible with Oracle. Now, it is this one that makes the test crash at the initializing phase : com.decathlon.tzatziki.steps.SpringJPASteps l.154
![image](https://user-images.githubusercontent.com/48682943/171862472-1757461a-62da-4f06-8e88-e8bf33bb18a7.png)
The error : bad SQL grammar [TRUNCATE xxxxx RESTART IDENTITY CASCADE]; nested exception is java.sql.SQLSyntaxErrorException: ORA-03290: Commande de troncation erronée - mot-clé CLUSTER ou TABLE absent
 
Thank you again for your help.
Best regards.
Sylvain G.

**Comment by mimfgg** [comment]
Hi Sylvain,

For this one we will probably have to do something specific depending on the SQL dialect. 

I don't think there will be a universal way ...

**Comment by PierreBock** [comment]
Hello @mimfgg 

Any news on your side ?

Best regards,

Pierre

**Comment by mimfgg** [comment]
Hi @PierreBock 

I haven't had time yet ... either you give it a try in your proje ct and open a PR.
Or we need to add an oracle docker image to be able to test it, and that's a bit more work.
