### ISSUE TITLE
Overriding the default log level

### ISSUE THREAD

**Issue by mamdouni** [Decathlon/tzatziki#74]
Hello,

The default log level of my project has been overridden by Tzatziki when doing tests. So my use case is : 
- I have some steps that will initialize a database connection
- if the log level is INFO -> I will print the db server name
- my default log level is WARN ( unless for the steps which is INFO)

![image](https://user-images.githubusercontent.com/61866853/171998941-882a8884-010b-4eb6-bcf5-4f2817d3627f.png)

So when running my scenario, the db info will print on the console via @Before method (**OrderDataSetSteps.java**)
![image](https://user-images.githubusercontent.com/61866853/171998486-77f5e419-4a39-44ef-bd27-82a1b4776f7d.png)

Well, nothing will be print because of @Before hook of the **LoggerSteps.java** class ( which override my log level to ERROR)
I fix this issue by re-overridden the log level after the execution of **LoggerSteps.java** in my **OrderDataSetSteps.java** class
![image](https://user-images.githubusercontent.com/61866853/171998870-3f1d8fd7-fd08-4d25-ba21-c14c53a0a6cd.png)

To fix the issue, i think that tzatziki should load the loggers based on the logback config file or to make it possible to [define loggers /Update LoggerSteps default log level] from the Steps file .

**Comment by mimfgg** [comment]
Yeah, it is on purpose that we don't use any of the xml files, it doesn't make so much sense since you can change all the loggers dynamically in the steps. I have added 2 methods in this PR https://github.com/Decathlon/tzatziki/pull/75.
